### ISSUE TITLE
Controlling using cmd_vel

### ISSUE THREAD

**Issue by BeenToJupiter** [PedroS235/tello_ros_wrapper#7]
Hey, can you tell me if you have tried controlling the drone using the cmd_vel topic and how accurate was it? I am using a similar ROS wrapper right now but the odometry data is inaccurate and in-turn making my /tf unreliable too. I am able to send cmd_vel to the drone but I cannot verify the accuracy.

**Comment by PedroS235** [comment]
Hi, I can send the cmd_vel yes, however like you said it's not sure if it is actually responding to the exact commands we send. The odometry is computed on the onboard computer and that's what I am publishing. From experiments, this odometry most of the time is drifting quite a lot and from testing I tried measuring the distance it travels and comparing with what we get, and it's not that accurate. I was thinking of perhaps making use of the IMU to try and compute and possibly fuse it together, but at the same time I believe that tello internally is already using it, so not sure if it would help much.

Only the rotation is accurate enough, that's all.

If you have any ideas to improve this, we could try something. Also, is this other wrapper using tellopy or any other library (in case it is made with python)

**Comment by BeenToJupiter** [comment]
> Hi, I can send the cmd_vel yes, however like you said it's not sure if it is actually responding to the exact commands we send. The odometry is computed on the onboard computer and that's what I am publishing. From experiments, this odometry most of the time is drifting quite a lot and from testing I tried measuring the distance it travels and comparing with what we get, and it's not that accurate. I was thinking of perhaps making use of the IMU to try and compute and possibly fuse it together, but at the same time I believe that tello internally is already using it, so not sure if it would help much.
> 
> Only the rotation is accurate enough, that's all.
> 
> If you have any ideas to improve this, we could try something. Also, is this other wrapper using tellopy or any other library (in case it is made with python)

Yes this is another ROS 1 wrapper using Tellopy [https://github.com/jordy-van-appeven/tello_driver]

I tried observing the odometry data and for me it switches from some real values to being zero randomly even when the drone is not at the origin and is moving. My goal was to make a tf publisher based on that odom data but I am having issues. The drone's origin is not consistent with every run. The tf values do not make sense. I might be doing it wrong but I also do not trust odometry data here.

My end goal is that the drone should be able to go to a goal using calculated command velocities.

**Comment by PedroS235** [comment]
> I tried observing the odometry data and for me it switches from some real values to being zero randomly even when the drone is not at the origin and is moving. My goal was to make a tf publisher based on that odom data but I am having issues. The drone's origin is not consistent with every run. The tf values do not make sense. I might be doing it wrong but I also do not trust odometry data here.

I also experienced that, indeed. 

> My end goal is that the drone should be able to go to a goal using calculated command velocities.

Have you consider using a VSLAM algorithm, like ORB-SLAM3 to obtain the poses? Other than that, I don't see any other solution for the moment.

**Comment by BeenToJupiter** [comment]
>> I also experienced that, indeed.
>
> Glad I am not the only one haha. I was questioning hardware of this particular drone I have.
> 
>>Have you consider using a VSLAM algorithm, like ORB-SLAM3 to obtain the poses? Other than that, I don't see any other solution for the moment.
>
> Yes I decided to use ORB-SLAM3 to obtain the estimated pose of my drone. I will have to move the drone really slow for that but I am hoping it will work.
